## What is Data Encoding?

### Data encoding is the process of converting categorical features into numerical values so that models can understand and process them effectively. This is essential for tasks such as predicting salary based on categorical features like degree.

## Why Data Encoding is Necessary

### Consider a dataset with features such as years of experience and degree, where the goal is to predict salary based on these features. The degree feature may have various categories like Bachelors, Masters, and PhD. These are categorical variables.

### Machine learning models cannot directly interpret categorical variables because they operate on numerical data. While humans understand the meaning of "Bachelors" or "PhD," models require numerical representations. Therefore, we need to convert categorical features into meaningful numerical values. This process is called data encoding.

## Types of Data Encoding
### 1)Nominal or One Hot Encoding
### 2)Label or Ordinal Encoding
### 3}Target Guided Ordinal Encoding

## One-Hot Encoding: Converts each category into a new binary column (0 or 1) representing its presence.

## Disadvantages of One Hot Encoding
#### If a categorical feature has many categories, such as 100, one hot encoding will create 100 new features, increasing dimensionality.
#### This leads to sparse matrices, where most values are zeros and only one value is one per row.
#### Sparse matrices can cause overfitting, where the model fits the training data too well but performs poorly on new data.

#### Therefore, one hot encoding is not recommended for features with many categories.

In [1]:
from sklearn.preprocessing import OneHotEncoder

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame({"color": ["red", "blue", "green", "red", "blue"]})
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [4]:
## Create instance of One Hot Encoder
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[["color"]])

In [5]:
## Sorted alphabatically
encoded.toarray()

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [6]:
encoded_df = pd.DataFrame(encoded.toarray(), columns=encoder.get_feature_names_out(["color"]))
encoded_df.head()

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [7]:
df_encoded = pd.concat([df, encoded_df], axis=1)
df_encoded.head()

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0

In [8]:
## Encoding New Data
new_data = [["blue"]]
encoded_new = encoder.transform(new_data)
encoded_new.toarray()

c:\Users\Inderjeet\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [9]:
encoded_df.head()

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0