# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.

In [5]:
import pandas as pd
import numpy as np
df=pd.DataFrame(np.random.randint(0,100,size=(6, 4)), columns=['A','B','C','D'])
print("Original DataFrame:")
df
df.set_index('A', inplace=True)
print("\nDataFrame after setting column 'A' as index:")
df

Original DataFrame:

DataFrame after setting column 'A' as index:

     B   C   D
A
60  97  94  30
50  99  90  67
76  74  24  68
10  84  11  98
66  38  82  50
26  29  22  62

2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

In [10]:
df=pd.DataFrame(np.random.randint(0,100,size=(3, 3)), columns=['A','B','C'], index=['X','Y','Z'])
print(df)
element = df.at['Y', 'B']
print(f"The element at row 'Y' and column 'B' is: {element}")

    A   B   C
X  22   1  72
Y  22  79  56
Z  25  27  35
The element at row 'Y' and column 'B' is: 79

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.

In [15]:
df = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C'], index=['0','1','2','3','4'])
print("Original DataFrame:")
print(df)

df['D'] = df['A'] * df['B']
print("DataFrame with new column:")
print(df)

df.loc['5'] = df.sum()
print("DataFrame with new row:")
print(df)

Original DataFrame:
    A   B   C
0  78  76   7
1  49  79  38
2  63  73  24
3  69  50  25
4  87  99  38
DataFrame with new column:
    A   B   C     D
0  78  76   7  5928
1  49  79  38  3871
2  63  73  24  4599
3  69  50  25  3450
4  87  99  38  8613
DataFrame with new row:
     A    B    C      D
0   78   76    7   5928
1   49   79   38   3871
2   63   73   24   4599
3   69   50   25   3450
4   87   99   38   8613
5  346  377  132  26461

2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

In [21]:
df = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)), columns=['A', 'B', 'C'], index=['0','1','2','3','4'])
print("Original DataFrame:")
print(df)
print("\n")
print("Row Sum")
row_sum = df.sum(axis=1)
print(row_sum)

print("\n")
print("Column Sum")
col_sum = df.sum(axis=0)
print(col_sum)

Original DataFrame:
    A   B   C
0  64  36  16
1  15  57  89
2  78  24  81
3  24  69  76
4  23  37  12


Row Sum
0    116
1    161
2    183
3    169
4     72
dtype: int64


Column Sum
A    204
B    223
C    274
dtype: int64

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.

In [31]:
df = pd.DataFrame(np.random.randint(1, 100, size=(5, 3)))
print("Original DataFrame:")
print(df)
print("\n")

df.iloc[0, 1] = np.nan
df.iloc[1, 2] = np.nan
df.iloc[3, 0] = np.nan

print("DataFrame with NaN values:")
print(df)

print("\n")
print("Filled NaN with mean value")
df.fillna(df.mean(), inplace=True)
df

Original DataFrame:
    0   1   2
0   1  65  24
1  18  24  18
2  60  75  38
3  44  41  53
4   6   3   6


DataFrame with NaN values:
      0     1     2
0   1.0   NaN  24.0
1  18.0  24.0   NaN
2  60.0  75.0  38.0
3   NaN  41.0  53.0
4   6.0   3.0   6.0


Filled NaN with mean value

       0      1      2
0   1.00  35.75  24.00
1  18.00  24.00  30.25
2  60.00  75.00  38.00
3  21.25  41.00  53.00
4   6.00   3.00   6.00

2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

In [38]:
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 4)))
print("Original DataFrame:")
print(df)
print("\n")

df.iloc[0, 1] = np.nan
df.iloc[1, 2] = np.nan

print("DataFrame with NaN values:")
print(df)

df.dropna(inplace= True)
print("\n")
print("Droped tables")
print(df)

Original DataFrame:
    0   1   2   3
0  99  60  68  27
1  41  19   3  91
2  38  64  11  81
3  80  21  66  51
4  50  23  15  83
5  18  52  64  12


DataFrame with NaN values:
    0     1     2   3
0  99   NaN  68.0  27
1  41  19.0   NaN  91
2  38  64.0  11.0  81
3  80  21.0  66.0  51
4  50  23.0  15.0  83
5  18  52.0  64.0  12


Droped tables
    0     1     2   3
2  38  64.0  11.0  81
3  80  21.0  66.0  51
4  50  23.0  15.0  83
5  18  52.0  64.0  12

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.

In [42]:
df = pd.DataFrame({'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Value': np.random.randint(1, 100, size=10)})
print("Original DataFrame:")
print(df)

grouping = df.groupby('Category')['Value'].agg(['sum','mean'])
print('\n')
print("Grouped DataFrame:")
print(grouping)

Original DataFrame:
  Category  Value
0        B     52
1        B     50
2        C     52
3        B     57
4        B     56
5        A      9
6        A     66
7        B     40
8        A     19
9        B     34


Grouped DataFrame:
          sum       mean
Category
A          94  31.333333
B         289  48.166667
C          52  52.000000

2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

In [47]:
df = pd.DataFrame({'Product': np.random.choice(['Product1', 'Product2', 'Product3', 'Product4', 'Product5', 'Product6'], size=10), 'Category': np.random.choice(['A', 'B', 'C'], size=10), 'Sales': np.random.randint(1, 100, size=10)})
print("Original DataFrame:")
print(df)

grouped_tables = df.groupby('Category')['Sales'].sum()
print("Grouped DataFrame and compuitng the total sales for each Category:")
print(grouped_tables)

Original DataFrame:
    Product Category  Sales
0  Product6        A     86
1  Product4        B     11
2  Product3        A     42
3  Product4        C     91
4  Product2        C     20
5  Product4        B     92
6  Product1        B     81
7  Product2        A     67
8  Product5        C     26
9  Product3        A     57
Grouped DataFrame and compuitng the total sales for each Category:
Category
A    252
B    184
C    137
Name: Sales, dtype: int32

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.

In [50]:
df1 = pd.DataFrame({'Key': ['A', 'B', 'C', 'D', 'G'], 'Value1': np.random.randint(1, 100, size=5)})
df2 = pd.DataFrame({'Key': ['A', 'B', 'C', 'E', 'F'], 'Value2': np.random.randint(1, 100, size=5)})
print("DataFrame 1:")
print(df1)
print("DataFrame 2:")
print(df2)

merged = pd.merge(df1, df2, on='Key')
print("Merged DataFrame:")
print(merged)

DataFrame 1:
  Key  Value1
0   A      67
1   B      36
2   C      43
3   D      55
4   G      23
DataFrame 2:
  Key  Value2
0   A      78
1   B      60
2   C      98
3   E      26
4   F      12
Merged DataFrame:
  Key  Value1  Value2
0   A      67      78
1   B      36      60
2   C      43      98

2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

In [52]:
df1 = pd.DataFrame({'A': np.random.randint(1, 100, size=3), 'B': np.random.randint(1, 100, size=3)})
df2 = pd.DataFrame({'C': np.random.randint(1, 100, size=3), 'D': np.random.randint(1, 100, size=3)})
print("DataFrame 1:")
print(df1)
print("DataFrame 2:")
print(df2)

concat_rows = pd.concat([df1, df2], axis=0)
print("Concatenated DataFrame (rows):")
print(concat_rows)

concat_columns = pd.concat([df1, df2], axis=1)
print("Concatenated DataFrame (columns):")
print(concat_columns)

DataFrame 1:
    A   B
0  72  88
1  70  51
2  56  98
DataFrame 2:
    C   D
0  67  39
1  27  24
2  85  66
Concatenated DataFrame (rows):
      A     B     C     D
0  72.0  88.0   NaN   NaN
1  70.0  51.0   NaN   NaN
2  56.0  98.0   NaN   NaN
0   NaN   NaN  67.0  39.0
1   NaN   NaN  27.0  24.0
2   NaN   NaN  85.0  66.0
Concatenated DataFrame (columns):
    A   B   C   D
0  72  88  67  39
1  70  51  27  24
2  56  98  85  66

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.

In [58]:
date_rng = pd.date_range(start='2022-01-01', end='2022-12-31', freq='D')
df = pd.DataFrame(date_rng, columns=['date'])
df['data'] = np.random.randint(0, 100, size=(len(date_rng)))
df.set_index('date', inplace=True)
print("Original DataFrame:")
print(df)

# Resample the DataFrame to compute the monthly mean of the values
monthly_mean = df.resample('ME').mean()
print("Monthly mean DataFrame:")
print(monthly_mean)

Original DataFrame:
            data
date
2022-01-01    76
2022-01-02    68
2022-01-03    88
2022-01-04    85
2022-01-05    20
...          ...
2022-12-27    83
2022-12-28    65
2022-12-29    42
2022-12-30    67
2022-12-31    13

[365 rows x 1 columns]
Monthly mean DataFrame:
                 data
date
2022-01-31  45.193548
2022-02-28  50.214286
2022-03-31  51.161290
2022-04-30  51.100000
2022-05-31  36.967742
2022-06-30  52.933333
2022-07-31  49.967742
2022-08-31  50.806452
2022-09-30  49.400000
2022-10-31  59.387097
2022-11-30  51.533333
2022-12-31  43.451613

2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

In [56]:
date_rng = pd.date_range(start='2022-01-01', end='2022-12-31', freq='D')
df = pd.DataFrame(date_rng, columns=['date'])
df['data'] = np.random.randint(0, 100, size=(len(date_rng)))
df.set_index('date', inplace=True)
print("Original DataFrame:")
print(df)

rolling_mean = df.rolling(window=7).mean()
print("Rolling mean DataFrame:")
print(rolling_mean)

Original DataFrame:
            data
date
2022-01-01    31
2022-01-02    20
2022-01-03    18
2022-01-04    68
2022-01-05    55
...          ...
2022-12-27     9
2022-12-28    38
2022-12-29    36
2022-12-30    46
2022-12-31    84

[365 rows x 1 columns]
Rolling mean DataFrame:
                 data
date
2022-01-01        NaN
2022-01-02        NaN
2022-01-03        NaN
2022-01-04        NaN
2022-01-05        NaN
...               ...
2022-12-27  42.857143
2022-12-28  45.857143
2022-12-29  41.428571
2022-12-30  41.857143
2022-12-31  53.142857

[365 rows x 1 columns]

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.

In [ ]:
arrays = [['A', 'A', 'B', 'B'], ['one', 'two', 'one', 'two']]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))
df = pd.DataFrame(np.random.randint(1, 100, size=(4, 3)), index=index, columns=['Value1', 'Value2', 'Value3'])
print("MultiIndex DataFrame:")
print(df)

print("Indexing at Category 'A':")
print(df.loc['A'])

print("Slicing at Category 'B' and SubCategory 'two':")
print(df.loc[('B', 'two')])

MultiIndex DataFrame:
                      Value1  Value2  Value3
Category SubCategory
A        one              86      17      13
         two              66      25       1
B        one              13      46      85
         two              77       7       6
Indexing at Category 'A':
             Value1  Value2  Value3
SubCategory
one              86      17      13
two              66      25       1
Slicing at Category 'B' and SubCategory 'two':
Value1    77
Value2     7
Value3     6
Name: (B, two), dtype: int32

2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

In [68]:
arrays = [['A', 'A', 'B', 'B'], ['one', 'two', 'one', 'two']]
index = pd.MultiIndex.from_arrays(arrays, names=('Category', 'SubCategory'))
df = pd.DataFrame(np.random.randint(1, 100, size=(4, 3)), index=index, columns=['Value1', 'Value2', 'Value3'])
print("MultiIndex DataFrame:")
print(df)

Sum=df.groupby(['Category', 'SubCategory']).sum()
print(Sum)

MultiIndex DataFrame:
                      Value1  Value2  Value3
Category SubCategory
A        one              75      33       5
         two              22      25      60
B        one              74      95      83
         two              57      14      76
                      Value1  Value2  Value3
Category SubCategory
A        one              75      33       5
         two              22      25      60
B        one              74      95      83
         two              57      14      76

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.

In [72]:
date_rng = pd.date_range(start='2022-01-01', end='2022-01-10', freq='D')
df = pd.DataFrame({'Date': np.random.choice(date_rng, size=20), 'Category': np.random.choice(['A', 'B', 'C'], size=20), 'Value': np.random.randint(1, 100, size=20)})
print("Original DataFrame:")
print(df)

# Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'
pivot_table = df.pivot_table(values='Value', index='Date', columns='Category', aggfunc='sum')
print("Pivot Table:")
print(pivot_table)

Original DataFrame:
         Date Category  Value
0  2022-01-02        B     13
1  2022-01-06        B     34
2  2022-01-08        C     63
3  2022-01-03        B     53
4  2022-01-06        A     72
5  2022-01-08        B     52
6  2022-01-03        C     97
7  2022-01-07        C     92
8  2022-01-08        A     94
9  2022-01-04        B      3
10 2022-01-06        A     87
11 2022-01-04        A     59
12 2022-01-07        C     26
13 2022-01-05        A     94
14 2022-01-07        C     85
15 2022-01-09        A     47
16 2022-01-06        B     97
17 2022-01-03        A      3
18 2022-01-03        B     38
19 2022-01-09        C     50
Pivot Table:
Category        A      B      C
Date
2022-01-02    NaN   13.0    NaN
2022-01-03    3.0   91.0   97.0
2022-01-04   59.0    3.0    NaN
2022-01-05   94.0    NaN    NaN
2022-01-06  159.0  131.0    NaN
2022-01-07    NaN    NaN  203.0
2022-01-08   94.0   52.0   63.0
2022-01-09   47.0    NaN   50.0

2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

In [79]:
date_rng = pd.date_range(start='2002', end='2022', freq='D')
df = pd.DataFrame({'Year': np.random.choice(date_rng, size=13), 'Quater': np.random.choice(['Q1', 'Q2', 'Q3', 'Q4'], size=13), 'Revenue': np.random.randint(1, 100, size=13)})
print("Original DataFrame:")
print(df)

# Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'
pivot_table = df.pivot_table(values='Revenue', index='Year', columns='Quater', aggfunc='mean')
print("Pivot Table:")
pivot_table

Original DataFrame:
         Year Quater  Revenue
0  2008-06-15     Q4       44
1  2020-08-19     Q1       62
2  2017-01-19     Q2       93
3  2014-08-10     Q1       67
4  2019-11-08     Q4       29
5  2012-10-01     Q1       72
6  2019-01-19     Q2       37
7  2018-03-17     Q3       44
8  2015-09-27     Q3       75
9  2006-10-26     Q4       51
10 2004-04-29     Q3       30
11 2004-04-27     Q1       30
12 2014-09-11     Q2       59
Pivot Table:

Quater        Q1    Q2    Q3    Q4
Year
2004-04-27  30.0   NaN   NaN   NaN
2004-04-29   NaN   NaN  30.0   NaN
2006-10-26   NaN   NaN   NaN  51.0
2008-06-15   NaN   NaN   NaN  44.0
2012-10-01  72.0   NaN   NaN   NaN
2014-08-10  67.0   NaN   NaN   NaN
2014-09-11   NaN  59.0   NaN   NaN
2015-09-27   NaN   NaN  75.0   NaN
2017-01-19   NaN  93.0   NaN   NaN
2018-03-17   NaN   NaN  44.0   NaN
2019-01-19   NaN  37.0   NaN   NaN
2019-11-08   NaN   NaN   NaN  29.0
2020-08-19  62.0   NaN   NaN   NaN

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.

In [75]:
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:")
print(df)

# Apply a lambda function to create a new column that is the sum of the existing columns
double = df.map(lambda x:x*2)
print("DataFrame with Sum column:")
print(double)

Original DataFrame:
    A   B   C
0  61  84  29
1  26  41  55
2  10  14  11
3  42  37  46
4  55  17  42
5  45  72  42
DataFrame with Sum column:
     A    B    C
0  122  168   58
1   52   82  110
2   20   28   22
3   84   74   92
4  110   34   84
5   90  144   84

2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

In [80]:
df = pd.DataFrame(np.random.randint(1, 100, size=(6, 3)), columns=['A', 'B', 'C'])
print("Original DataFrame:")
print(df)

# Apply a lambda function to create a new column that is the sum of the existing columns
df['Sum'] = df.apply(lambda row: row.sum(), axis=1)
print("DataFrame with Sum column:")
print(df)

Original DataFrame:
    A   B   C
0  49  46  66
1  54   3  90
2  51  33  84
3  52  56  38
4  42  84   1
5  56  42  87
DataFrame with Sum column:
    A   B   C  Sum
0  49  46  66  161
1  54   3  90  147
2  51  33  84  168
3  52  56  38  146
4  42  84   1  127
5  56  42  87  185

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.

In [70]:
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print("Original Series:")
print(text_data)

# Convert all the strings to uppercase
uppercase_data = text_data.str.upper()
print("Uppercase Series:")
print(uppercase_data)

Original Series:
0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: object
Uppercase Series:
0         APPLE
1        BANANA
2        CHERRY
3          DATE
4    ELDERBERRY
dtype: object

2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [71]:
text_data = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])
print("Original Series:")
print(text_data)

char_data = text_data.str[:3]
print("Three Characters of each string:")
print(char_data)

Original Series:
0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: object
Three Characters of each string:
0    app
1    ban
2    che
3    dat
4    eld
dtype: object